spring.application.name=AshokNagarProperties
server.port=3060
spring.datasource.url=jdbc:mysql://localhost:3306/propertydealer?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=root

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.main.allow-bean-definition-overriding=true

spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
springdoc.override-with-generic-response=false
spring.jpa.hibernate.ddl-auto=update
jwt.secret=REPLACE_WITH_STRONG_SECRET
jwt.expirationMs=86400000

sms.api.url=https://api.msg91.com/api/v5/otp
sms.api.key=YOUR_SMS_API_KEY
sms.sender.id=PRDEAL

app.admin.emails=admin1@example.com,admin2@example.com
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=shivsinghrajput78611@gmail.com
spring.mail.password=nheznbbrswoxtipm
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=20MB
spring.servlet.multipart.max-request-size=20MB

